image: node:16.13.0

pipelines:
  branches:
    master:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            - build/**
      - step:
          name: Deploy artifacts using SCP to PROD
          deployment: production
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                PASSWORD: $PASSWORD
                DELETE_FLAG: 'true'
                REMOTE_PATH: '/var/apps/hod/frontend'
                LOCAL_PATH: 'build/*'
